package com.jid.springhueclient.clip.model.room;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum HueRoomArchetype {

    @JsonProperty("living_room")
    LIVING_ROOM,
    @JsonProperty("kitchen")
    KITCHEN,
    @JsonProperty("dining")
    DINING,
    @JsonProperty("bedroom")
    BEDROOM,
    @JsonProperty("kids_bedroom")
    KIDS_BEDROOM,
    @JsonProperty("bathroom")
    BATHROOM,
    @JsonProperty("nursery")
    NURSERY,
    @JsonProperty("recreation")
    RECREATION,
    @JsonProperty("office")
    OFFICE,
    @JsonProperty("gym")
    GYM,
    @JsonProperty("hallway")
    HALLWAY,
    @JsonProperty("toilet")
    TOILET,
    @JsonProperty("front_door")
    FRONT_DOOR,
    @JsonProperty("garage")
    GARAGE,
    @JsonProperty("terrace")
    TERRACE,
    @JsonProperty("garden")
    GARDEN,
    @JsonProperty("driveway")
    DRIVEWAY,
    @JsonProperty("carport")
    CARPORT,
    @JsonProperty("home")
    HOME,
    @JsonProperty("downstairs")
    DOWNSTAIRS,
    @JsonProperty("upstairs")
    UPSTAIRS,
    @JsonProperty("top_floor")
    TOP_FLOOR,
    @JsonProperty("attic")
    ATTIC,
    @JsonProperty("guest_room")
    GUEST_ROOM,
    @JsonProperty("staircase")
    STAIRCASE,
    @JsonProperty("lounge")
    LOUNGE,
    @JsonProperty("man_cave")
    MAN_CAVE,
    @JsonProperty("computer")
    COMPUTER,
    @JsonProperty("studio")
    STUDIO,
    @JsonProperty("music")
    MUSIC,
    @JsonProperty("tv")
    TV,
    @JsonProperty("reading")
    READING,
    @JsonProperty("closet")
    CLOSET,
    @JsonProperty("storage")
    STORAGE,
    @JsonProperty("laundry_room")
    LAUNDRY_ROOM,
    @JsonProperty("balcony")
    BALCONY,
    @JsonProperty("porch")
    PORCH,
    @JsonProperty("barbecue")
    BARBECUE,
    @JsonProperty("pool")
    POOL,
    @JsonProperty("other")
    OTHER,
    ;
}
