package com.jid.springhueclient.clip.model;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum HueResourceArchetype {

    @JsonProperty("unknown_archetype")
    UNKNOWN_ARCHETYPE,
    @JsonProperty("classic_bulb")
    CLASSIC_BULB,
    @JsonProperty("sultan_bulb")
    SULTAN_BULB,
    @JsonProperty("flood_bulb")
    FLOOD_BULB,
    @JsonProperty("spot_bulb")
    SPOT_BULB,
    @JsonProperty("candle_bulb")
    CANDLE_BULB,
    @JsonProperty("luster_bulb")
    LUSTER_BULB,
    @JsonProperty("pendant_round")
    PENDANT_ROUND,
    @JsonProperty("pendant_long")
    PENDANT_LONG,
    @JsonProperty("ceiling_round")
    CEILING_ROUND,
    @JsonProperty("ceiling_square")
    CEILING_SQUARE,
    @JsonProperty("floor_shade")
    FLOOR_SHADE,
    @JsonProperty("floor_lantern")
    FLOOR_LANTERN,
    @JsonProperty("table_shade")
    TABLE_SHADE,
    @JsonProperty("recessed_ceiling")
    RECESSED_CEILING,
    @JsonProperty("recessed_floor")
    RECESSED_FLOOR,
    @JsonProperty("single_spot")
    SINGLE_SPOT,
    @JsonProperty("double_spot")
    DOUBLE_SPOT,
    @JsonProperty("table_wash")
    TABLE_WASH,
    @JsonProperty("wall_lantern")
    WALL_LANTERN,
    @JsonProperty("wall_shade")
    WALL_SHADE,
    @JsonProperty("flexible_lamp")
    FLEXIBLE_LAMP,
    @JsonProperty("ground_spot")
    GROUND_SPOT,
    @JsonProperty("wall_spot")
    WALL_SPOT,
    @JsonProperty("plug")
    PLUG,
    @JsonProperty("hue_go")
    HUE_GO,
    @JsonProperty("hue_lightstrip")
    HUE_LIGHTSTRIP,
    @JsonProperty("hue_iris")
    HUE_IRIS,
    @JsonProperty("hue_bloom")
    HUE_BLOOM,
    @JsonProperty("bollard")
    BOLLARD,
    @JsonProperty("wall_washer")
    WALL_WASHER,
    @JsonProperty("hue_play")
    HUE_PLAY,
    @JsonProperty("vintage_bulb")
    VINTAGE_BULB,
    @JsonProperty("vintage_candle_bulb")
    VINTAGE_CANDLE_BULB,
    @JsonProperty("ellipse_bulb")
    ELLIPSE_BULB,
    @JsonProperty("triangle_bulb")
    TRIANGLE_BULB,
    @JsonProperty("small_globe_bulb")
    SMALL_GLOBE_BULB,
    @JsonProperty("large_globe_bulb")
    LARGE_GLOBE_BULB,
    @JsonProperty("edison_bulb")
    EDISON_BULB,
    @JsonProperty("christmas_tree")
    CHRISTMAS_TREE,
    @JsonProperty("string_light")
    STRING_LIGHT,
    @JsonProperty("hue_centris")
    HUE_CENTRIS,
    @JsonProperty("hue_lightstrip_tv")
    HUE_LIGHTSTRIP_TV,
    @JsonProperty("hue_lightstrip_pc")
    HUE_LIGHTSTRIP_PC,
    @JsonProperty("hue_tube")
    HUE_TUBE,
    @JsonProperty("hue_signe")
    HUE_SIGNE,
    @JsonProperty("pendant_spot")
    PENDANT_SPOT,
    @JsonProperty("ceiling_horizontal")
    CEILING_HORIZONTAL,
    @JsonProperty("ceiling_tube")
    CEILING_TUBE,
    @JsonProperty("up_and_down")
    UP_AND_DOWN,
    @JsonProperty("up_and_down_up")
    UP_AND_DOWN_UP,
    @JsonProperty("up_and_down_down")
    UP_AND_DOWN_DOWN,
    @JsonProperty("hue_floodlight_camera")
    HUE_FLOODLIGHT_CAMERA,
    @JsonProperty("twilight")
    TWILIGHT,
    @JsonProperty("twilight_front")
    TWILIGHT_FRONT,
    @JsonProperty("twilight_back")
    TWILIGHT_BACK,
    @JsonProperty("hue_play_wallwasher")
    HUE_PLAY_WALLWASHER,
    @JsonProperty("hue_omniglow")
    HUE_OMNIGLOW,
    @JsonProperty("hue_neon")
    HUE_NEON,
    @JsonProperty("string_globe")
    STRING_GLOBE,
    @JsonProperty("string_permanent")
    STRING_PERMANENT,

    ;
}
